[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[phases.caddy]
cmds = []

[start]
cmd = "npx vite preview --host 0.0.0.0 --port $PORT"
